// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// ConfigureSAMLHandlerFunc turns a function with the right signature into a configure s a m l handler
type ConfigureSAMLHandlerFunc func(ConfigureSAMLParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ConfigureSAMLHandlerFunc) Handle(params ConfigureSAMLParams) middleware.Responder {
	return fn(params)
}

// ConfigureSAMLHandler interface for that can handle valid configure s a m l params
type ConfigureSAMLHandler interface {
	Handle(ConfigureSAMLParams) middleware.Responder
}

// NewConfigureSAML creates a new http.Handler for the configure s a m l operation
func NewConfigureSAML(ctx *middleware.Context, handler ConfigureSAMLHandler) *ConfigureSAML {
	return &ConfigureSAML{Context: ctx, Handler: handler}
}

/*ConfigureSAML swagger:route GET /saml configureSAML

null

null

*/
type ConfigureSAML struct {
	Context *middleware.Context
	Handler ConfigureSAMLHandler
}

func (o *ConfigureSAML) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewConfigureSAMLParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
