// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/Magicking/rc-ge-ch-pdf/models"
)

// DelreceiptsOKCode is the HTTP code returned for type DelreceiptsOK
const DelreceiptsOKCode int = 200

/*DelreceiptsOK delreceipts o k

swagger:response delreceiptsOK
*/
type DelreceiptsOK struct {
}

// NewDelreceiptsOK creates DelreceiptsOK with default headers values
func NewDelreceiptsOK() *DelreceiptsOK {
	return &DelreceiptsOK{}
}

// WriteResponse to the client
func (o *DelreceiptsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
}

/*DelreceiptsDefault Internal error

swagger:response delreceiptsDefault
*/
type DelreceiptsDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDelreceiptsDefault creates DelreceiptsDefault with default headers values
func NewDelreceiptsDefault(code int) *DelreceiptsDefault {
	if code <= 0 {
		code = 500
	}

	return &DelreceiptsDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the delreceipts default response
func (o *DelreceiptsDefault) WithStatusCode(code int) *DelreceiptsDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the delreceipts default response
func (o *DelreceiptsDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the delreceipts default response
func (o *DelreceiptsDefault) WithPayload(payload *models.Error) *DelreceiptsDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delreceipts default response
func (o *DelreceiptsDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DelreceiptsDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
