// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
	strfmt "github.com/go-openapi/strfmt"
	swag "github.com/go-openapi/swag"
)

// MonitoringHandlerFunc turns a function with the right signature into a monitoring handler
type MonitoringHandlerFunc func(MonitoringParams) middleware.Responder

// Handle executing the request and returning a response
func (fn MonitoringHandlerFunc) Handle(params MonitoringParams) middleware.Responder {
	return fn(params)
}

// MonitoringHandler interface for that can handle valid monitoring params
type MonitoringHandler interface {
	Handle(MonitoringParams) middleware.Responder
}

// NewMonitoring creates a new http.Handler for the monitoring operation
func NewMonitoring(ctx *middleware.Context, handler MonitoringHandler) *Monitoring {
	return &Monitoring{Context: ctx, Handler: handler}
}

/*Monitoring swagger:route GET /sonde monitoring

Retourne quatres flag correspondant respectivement à la bonne connexion à un noeud Infura, la balance supérieure à 1 ETH, supérieure à 0,1 ETH et le bon fonctionnement d'une requête vers la base de données.

Retourne quatres flag correspondant respectivement à la bonne connexion à un noeud Infura, la balance supérieure à 1 ETH, supérieure à 0,1 ETH et le bon fonctionnement d'une requête vers la base de données


*/
type Monitoring struct {
	Context *middleware.Context
	Handler MonitoringHandler
}

func (o *Monitoring) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewMonitoringParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}

// MonitoringOKBody monitoring o k body
// swagger:model MonitoringOKBody
type MonitoringOKBody struct {

	// balance error threshold exceeded
	BalanceErrorThresholdExceeded bool `json:"balanceErrorThresholdExceeded,omitempty"`

	// balance warning threshold exceeded
	BalanceWarningThresholdExceeded bool `json:"balanceWarningThresholdExceeded,omitempty"`

	// ethereum active
	EthereumActive bool `json:"ethereumActive,omitempty"`

	// persistence active
	PersistenceActive bool `json:"persistenceActive,omitempty"`
}

// Validate validates this monitoring o k body
func (o *MonitoringOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *MonitoringOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *MonitoringOKBody) UnmarshalBinary(b []byte) error {
	var res MonitoringOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
