// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// Sonde sonde
// swagger:model Sonde
type Sonde struct {

	// balance error threshold exceeded
	BalanceErrorThresholdExceeded bool `json:"balanceErrorThresholdExceeded"`

	// balance warning threshold exceeded
	BalanceWarningThresholdExceeded bool `json:"balanceWarningThresholdExceeded"`

	// ethereum active
	EthereumActive bool `json:"ethereumActive"`

	// persistence active
	PersistenceActive bool `json:"persistenceActive"`
}

// Validate validates this sonde
func (m *Sonde) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Sonde) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Sonde) UnmarshalBinary(b []byte) error {
	var res Sonde
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
